### PR TITLE
redo the website making use of components properly

### PR DESCRIPTION
**Pull request by jdonszelmann**
I realise this is an almost impossible to review PR. The funny thing is, it doesn't actually change a single visible thing. I just made it so that we can maintain it much better from now on. There now is

* Basically a single layout all pages use
* Components with *scoped scss* for everything, and very few global styles
* Fewer css-resets leading to unexpected behavior
* more alt-text and other accessibility features
* less code duplication
* More semantic components

### CODE REVIEW

**Comment by erikjee** [comment]
@jdonszelmann this was long overdue, so thanks for doing this. But .... I see a bunch of things changed in the layout (understandably after a big refactor); see screenshots below.

There is likely a lot more we need to check, as I only checked the homepage now.

- other current pages + all the pages that are currently not in use (schedule, unconf, speakers)
- mobile!! (all breakpoints)

I had a quick look at the other pages and that doesn't look like a lot changed. So maybe it is not too bad. Looks like text alignment (center, not left aligned) is an issue, and sponsor boxes. 

Another thing: I would prefer if Erwin does a review, but he is on a holiday break. 
Note: I haven't looked at the code yet, just the UI itself.

It would be nice to merge this soon though, so maybe skip Erwin's review, so that we don't have to maintain two branches.

speakers (heading changed)
about
sponsors
hero

**Comment by jdonszelmann** [comment]
fixed the homepage hero

**Comment by tertsdiepraam** [comment]
I much prefer this to the existing code. I noticed that the typography is all getting a bit smaller, which isn't great imo. Also headings are missing some padding below. Otherwise, it's looking great.

**Review by tertsdiepraam — APPROVED** [review]

**Comment by tertsdiepraam** [comment]
image

Here too, the reset is doing a bit too much because there should be some space between the paragraphs.

**Comment by erikjee** [comment]
@jdonszelmann @tertsdiepraam I found two minor changes on mobile:

1) menu spacing is now smaller (sort of relevant for ux)
2) spacing around city images has increased. Is a bit much now. Both above and below the images.

Screens are from ubuntu/chrome. Left is new, right is old:

Screenshot from 2024-09-03 16-43-56
Screenshot from 2024-09-03 16-43-28

**Pull request merged**
